#!/usr/bin/env php
<?php
$appName = isset($argv[1]) ? $argv[1] : array_pop(explode('/', getcwd()));
$phar = new Phar($appName . '.phar', 0, $appName . '.phar');

$phar->buildFromIterator(
    new RecursiveIteratorIterator(new RecursiveDirectoryIterator(getcwd(), FilesystemIterator::CURRENT_AS_SELF)),
    __DIR__
);

$phar->setStub($phar->createDefaultStub('bin/console'));
